### ISSUE TITLE
--Feature Request--

### ISSUE THREAD

**Issue by KeyboardChampion** [OrigamingWasTaken/appleblox#2]
is it possible for you to add a toggle that disables Roblox textures/lighting? this will speed up the game a decent amount for me since my computer isn't very fast.

**Comment by OrigamingWasTaken** [comment]
Hey, sure! I'll try to see if it is possible to disable lightning and if it has performance improvements (maybe disable shadows)? But from what i've seen, disabling textures doesn't really improve performance, I may be wrong tho.

Also just curious, does the app work correctly for you? I'm asking this because I haven't been able to test it on another machine than mine.

**Comment by OrigamingWasTaken** [comment]
The Bloxstrap SDK isn't implemented yet... I should probably gray out the non-working features. In the future, it will try to mimic the [SDK of Bloxstrap](https://github.com/pizzaboxer/bloxstrap/wiki/Integrating-Bloxstrap-functionality-into-your-game) to support multiple custom functions (controlling roblox window size from a game, things like that)

**Comment by OrigamingWasTaken** [comment]
I've done my research and I don't think it's possible to disable lightning, the best you can do is try Voxel lightning in the Fastflags tab. Also, changing the textures is only possible for the base roblox textures, which will also not give any performance improvement.
